services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://${WIKI_PG_USER}:${WIKI_PG_PASS}@postgres:5432/${WIKI_PG_DB}
      REDIS_URL: ${REDIS_URL}
      URL: https://${DOMAIN}
      PORT: 3000
      PGSSLMODE: disable

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${WIKI_PG_USER}
      POSTGRES_PASSWORD: ${WIKI_PG_PASS}
      POSTGRES_DB: ${WIKI_PG_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${WIKI_PG_DB}", "-U", "${WIKI_PG_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3

  dex:
    image: dexidp/dex:v2.35.3
    ports:
      - "5556:5556"
    volumes:
      - ./dex:/etc/dex
    command: ["dex", "serve", "/etc/dex/config.yaml"]

volumes:
  storage-data:
  database-data:
